- name: Create Kubernetes config folder
  ansible.builtin.file:
    path: "{{ playbook_dir }}/.kube"
    # owner: "{{ ansible_user }}"
    # group: "{{ ansible_user }}"
    state: directory
    # mode: '0750'

- name: Get Kubeconfig for EKS Clusters
  ansible.builtin.command: aws eks update-kubeconfig --name {{ cluster_name }} --kubeconfig {{ playbook_dir }}/.kube/config --region {{ aws_region }}
  when: cloud_provider == "aws"

  # Role Git - https://github.com/nasx/umbrella-gitops
- name: Add roles to Cluster
  ansible.builtin.include_role:
    name: acm-add-spoke
  vars:
    acm:
      acm_hub_kubeconfig: "{{ acm_hub_kubeconfig }}"
      spokes:
        - name: "{{ cluster_name }}"
          kubeconfig: "{{ playbook_dir }}/.kube/config"
  when: not delete