- name: Create SSH Key Pair tasks
  ansible.builtin.include_tasks: create_key_pair.yml

- name: Create VPC tasks
  ansible.builtin.include_tasks: create_vpc.yml

- name: Create Security Group tasks
  ansible.builtin.include_tasks: create_security_group.yml

- name: Create Subnet tasks
  ansible.builtin.include_tasks: create_subnet.yml

- name: Create IAM role tasks
  ansible.builtin.include_tasks: create_iam_role.yml

- name: Create Internet Gateway tasks
  ansible.builtin.include_tasks: create_igw.yml

- name: Create Route Table tasks
  ansible.builtin.include_tasks: create_rt_table.yml

- name: Provision EKS Cluster tasks
  ansible.builtin.include_tasks: create_eks.yml
